export const RECEIVE_CATEGORIES = "RECEIVE_CATEGORIES";

export const RECEIVE_POSTS = "RECEIVE_POSTS";
export const RECEIVE_POST = "RECEIVE_POST";
export const POST_UP_VOTE = "POST_UP_VOTE";
export const POST_DOWN_VOTE = "POST_DOWN_VOTE";
export const DELETE_POST = "DELETE_POST";
export const UPDATE_POST = "UPDATE_POST";
export const CREATE_POST = "CREATE_POST";

export const SET_SORT_BY = "SET_SORT_BY";
export const TOGGLE_SORT_ORDER = "TOGGLE_SORT_ORDER";

export const RECEIVE_COMMENTS = "RECEIVE_COMMENTS";
export const COMMENT_UP_VOTE = "COMMENT_UP_VOTE";
export const COMMENT_DOWN_VOTE = "COMMENT_DOWN_VOTE";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";

export const SET_ERROR = "SET_ERROR";
export const CATEGORIES_LOADING_DATA = "CATEGORIES_LOADING_DATA"
export const POSTS_LOADING_DATA = "POSTS_LOADING_DATA"
export const POST_DETAIL_LOADING_DATA = "POST_DETAIL_LOADING_DATA"
export const COMMENTS_LOADING_DATA = "COMMENTS_LOADING_DATA"
